services:
 bind9:
  container_name: the-one-you-want
  image: ubuntu/bind9:latest
  environment:
   - BIND9_USER=root
   - TZ=Your-zone
  ports:
   - "53:53/tcp" # Bind need the port 53 in TCP and UDP
   - "53:53/udp"
  volumes:
   - ./config:/etc/bind # This is for the files of the DNS zone
   - ./cache:/var/cache/bind
   - ./records:/var/lib/bind
  restart: unless-stopped
