services:
 bind9:
  container_name: container-name
  image: ubuntu/bind9:latest
  environment:
   - BIND9_USER=root
   - TZ=live-zone
  ports:
   - "53:53/tcp" # Bind9 need the port 53 in TCP and UDP to be open
   - "53:53/udp"
  volumes:
   - ./config:/etc/bind
   - ./cache:/var/cache/bind
   - ./records:/var/lib/bind
  restart: unless-stopped
